import type { AnalysisResult, TestReport } from '../types.js';

/**
 * Render the analysis as GitHub-flavored markdown, suitable for a PR comment.
 */
export function formatMarkdown(result: AnalysisResult): string {
  const lines: string[] = [];

  lines.push('## 🎯 Flaky Test Detector');
  lines.push('');
  lines.push(
    `_${result.totalRuns} runs · ${result.totalTests} unique tests · threshold ${(result.config.flakeThreshold * 100).toFixed(0)}%_`,
  );
  lines.push('');

  if (!result.hasFlakiness && result.stableFail.length === 0) {
    lines.push(`✅ **No flakiness detected across ${result.totalRuns} runs.**`);
    lines.push('');
    lines.push(`- ${result.stablePass.length} stable · ${result.skipped.length} skipped`);
    return lines.join('\n');
  }

  if (result.flaky.length > 0) {
    lines.push(`### ⚠️ Flaky (${result.flaky.length})`);
    lines.push('');
    lines.push('| Test | Flake rate | Failures / runs |');
    lines.push('|---|---|---|');
    for (const r of result.flaky) lines.push(rowFlaky(r));
    lines.push('');
  }

  if (result.stableFail.length > 0) {
    lines.push(`### ❌ Broken (${result.stableFail.length}) — always failing, likely real bugs`);
    lines.push('');
    lines.push('| Test | Last failure |');
    lines.push('|---|---|');
    for (const r of result.stableFail) lines.push(rowFail(r));
    lines.push('');
  }

  if (result.sparse.length > 0) {
    lines.push(`### ~ Sparse (${result.sparse.length})`);
    lines.push('');
    lines.push('_Observed in fewer runs than the minimum threshold — likely only ran in a matrix cell._');
    lines.push('');
  }

  lines.push('---');
  lines.push(
    `<sub>✓ ${result.stablePass.length} stable · ⊘ ${result.skipped.length} skipped · Generated by [flaky-test-detector](https://github.com/surya098-pixel/flaky-test-detector)</sub>`,
  );

  return lines.join('\n');
}

function rowFlaky(r: TestReport): string {
  const pct = (r.flakeRate * 100).toFixed(0);
  const label = escapeCell(`${r.suite} › ${r.name}`);
  return `| ${label} | **${pct}%** | ${r.failures + r.errors} / ${r.runs - r.skips} |`;
}

function rowFail(r: TestReport): string {
  const label = escapeCell(`${r.suite} › ${r.name}`);
  const msg = r.lastFailureMessage ? escapeCell(trunc(r.lastFailureMessage, 200)) : '_(no message)_';
  return `| ${label} | ${msg} |`;
}

function escapeCell(s: string): string {
  return s.replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

function trunc(s: string, n: number): string {
  const oneLine = s.replace(/\s+/g, ' ').trim();
  return oneLine.length <= n ? oneLine : oneLine.slice(0, n) + '…';
}
